all:
	gcc -std=gnu99 -Wall namelist.c stringlist.c -o namelist

debug:
	gcc -m32 -std=gnu99 -Wall namelist.c stringlist.c -g -o namelist

32bit:
	gcc -m32 -std=gnu99 -Wall namelist.c stringlist.c -g -o namelist